package com.fictitious.insurance.securitylab;

import java.net.URI;

public final class SecurityLabExamples {

    private SecurityLabExamples() {
    }

    // Intentional CRITICAL finding for the exercise.
    public static String executeUserCommand(String command) {
        return "Command execution is disabled by security policy";
    }
    // Intentional HIGH finding that the instructor will classify as a false positive:
    // the reference is generated by a trusted internal risk integration, not by HTTP input.
    public static URI buildTrustedRiskUri(String internalRiskReference) {
        return URI.create("https://risk.example/api/" + internalRiskReference);
    }

    // Intentional MEDIUM finding: visible in the report but non-blocking under the policy.
    public static void logExerciseMessage(String message) {
        System.out.println(message);
    }
}
