spring:
  application:
    name: insurance-core-api

server:
  port: 8080

insurance:
  integrations:
    risk:
      base-url: https://httpbin.org

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
