#!/usr/bin/env python3
"""Build a polished GitHub Actions Job Summary for the DevSecOps metrics lab."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = json.loads((ROOT / "devsecops-metrics.json").read_text(encoding="utf-8"))
SARIF = json.loads((ROOT.parent / "devsecops-results.sarif").read_text(encoding="utf-8"))


def pct(a, b):
    return a / b * 100 if b else 0


p = DATA["program"]
ed = DATA["early_detection"]
le = DATA["leakage"]
sec = DATA["security"]
q = DATA["quality"]
f = DATA["flow"]

coverage = pct(p["protected_repositories"], p["repositories"])
scanning = pct(p["prs_with_scanning"], p["prs"])
enforcement = pct(p["prs_with_gate"], p["prs"])
corrected = pct(p["prs_corrected"], p["prs"])
edr = pct(ed["detected_in_pr"], ed["detected_in_pr"] + ed["detected_in_ci"] + ed["escaped_to_production"])
prevention = pct(le["blocked_by_push_protection"], le["confirmed_secrets"])
sla = pct(sec["resolved_within_sla"], sec["resolved_total"])
security_share = pct(f["security_minutes"], f["pipeline_minutes"])

results = SARIF["runs"][0]["results"]

lines = []
lines += [
    "# 🛡️ DevSecOps Metrics Dashboard",
    "",
    "> **Insurance Core API · Executive + Technical Security Readout**",
    "> This report connects program metrics with the individual SARIF findings generated by the lab.",
    "",
    "## 🎯 Executive Snapshot",
    "",
    "| Dimension | KPI | Result | Signal |",
    "|---|---|---:|:---:|",
    f"| **Adoption** | Repository coverage | **{coverage:.0f}%** | {'🟢' if coverage >= 90 else '🟡'} |",
    f"| **Prevention** | Early Detection Rate (EDR) | **{edr:.0f}%** | {'🟢' if edr >= 75 else '🟡'} |",
    f"| **Leakage** | Secret prevention rate | **{prevention:.1f}%** | {'🟢' if prevention >= 85 else '🟡'} |",
    f"| **Security** | MTTR | **{sec['mttr_days']:.1f} days** | {'🟢' if sec['mttr_days'] <= sec['sla_target_days'] else '🔴'} |",
    f"| **Flow** | Security share of pipeline | **{security_share:.1f}%** | ℹ️ |",
    "",
    "---",
    "",
    "## 📈 1. Adoption & Enforcement",
    "",
    "| Metric | Result | Detail |",
    "|---|---:|---|",
    f"| Repository coverage | **{coverage:.1f}%** | {p['protected_repositories']} / {p['repositories']} repositories |",
    f"| PRs with scanning | **{scanning:.1f}%** | {p['prs_with_scanning']} / {p['prs']} PRs |",
    f"| PRs with Quality Gate | **{enforcement:.1f}%** | {p['prs_with_gate']} / {p['prs']} PRs |",
    f"| PRs corrected | **{corrected:.1f}%** | {p['prs_corrected']} / {p['prs']} PRs |",
    "",
    "## 🕵️ 2. Early Detection",
    "",
    "| Detection point | Findings |",
    "|---|---:|",
    f"| Detected in PR | **{ed['detected_in_pr']}** |",
    f"| Detected in CI | **{ed['detected_in_ci']}** |",
    f"| Escaped to production | **{ed['escaped_to_production']}** |",
    f"| **EDR** | **{edr:.1f}%** |",
    "",
    "## 🔐 3. Leakage Funnel",
    "",
    "| Stage | Count |",
    "|---|---:|",
    f"| Detected secrets | **{le['detected_secrets']}** |",
    f"| Confirmed secrets | **{le['confirmed_secrets']}** |",
    f"| Blocked by push protection | **{le['blocked_by_push_protection']}** |",
    f"| Bypassed | **{le['bypassed']}** |",
    f"| Exposed | **{le['exposed']}** |",
    f"| **Prevention rate** | **{prevention:.1f}%** |",
    "",
    "## 🚨 4. Security Posture",
    "",
    "| KPI | Result |",
    "|---|---:|",
    f"| Open alerts | **{sec['open_alerts']}** |",
    f"| 🔴 Critical | **{sec['critical_open']}** |",
    f"| 🟠 High | **{sec['high_open']}** |",
    f"| 🟡 Medium | **{sec['medium_open']}** |",
    f"| ⚪ Low | **{sec['low_open']}** |",
    f"| Average age | **{sec['average_age_days']} days** |",
    f"| MTTR | **{sec['mttr_days']:.1f} days** |",
    f"| Resolved within SLA | **{sla:.1f}%** |",
    "",
    "## 🧪 5. Quality",
    "",
    "| Metric | Result |",
    "|---|---:|",
    f"| New-code coverage | **{q['coverage_new_code_pct']:.1f}%** |",
    f"| Bugs | **{q['bugs']}** |",
    f"| Code smells | **{q['code_smells']}** |",
    f"| Duplication | **{q['duplication_pct']:.1f}%** |",
    f"| High-complexity items | **{q['high_complexity_items']}** |",
    "",
    "## ⚡ 6. Flow & Developer Experience",
    "",
    "| Metric | Result |",
    "|---|---:|",
    f"| PR cycle | **{f['pr_cycle_minutes']} min** |",
    f"| Review time | **{f['review_minutes']} min** |",
    f"| Pipeline duration | **{f['pipeline_minutes']} min** |",
    f"| Security duration | **{f['security_minutes']} min** |",
    f"| **Security share** | **{security_share:.1f}%** of pipeline |",
    f"| Lead time | **{f['lead_time_hours']} h** |",
    f"| Deployment frequency | **{f['deployment_frequency_per_week']}/week** |",
    f"| Change failure rate | **{f['change_failure_rate_pct']:.1f}%** |",
    "",
    "---",
    "",
    "## 📄 7. SARIF Findings",
    "",
    f"> **{len(results)} findings** were generated in `devsecops-results.sarif` and uploaded to GitHub Code Scanning.",
    "",
    "| Severity | Rule | Category | Evidence / Message |",
    "|:---:|---|---|---|",
]

for r in results:
    props = r.get("properties", {})
    severity = props.get("severity", "-")
    icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "⚪"}.get(severity, "⚪")
    message = r["message"]["text"]
    lines.append(f"| {icon} **{severity}** | `{r['ruleId']}` | `{props.get('category', '-')}` | {message} |")

lines += [
    "",
    "<details>",
    "<summary><strong>🔎 View SARIF technical details</strong></summary>",
    "",
    "| Rule | Level | Metric | Location |",
    "|---|:---:|---|---|",
]

for r in results:
    props = r.get("properties", {})
    loc = r.get("locations", [{}])[0].get("physicalLocation", {}).get("artifactLocation", {}).get("uri", "-")
    lines.append(f"| `{r['ruleId']}` | `{r['level']}` | `{props.get('metric', '-')}` | `{loc}` |")

lines += [
    "",
    "</details>",
    "",
    "## 💡 8. What should we discuss?",
    "",
    "1. **Adoption:** Is 100% scanning enough, or do we need 100% enforcement?",
    "2. **Prevention:** Why are 4 findings still escaping to production?",
    "3. **Security:** What is the business impact of the 1 Critical and 4 High alerts?",
    "4. **Leakage:** What does the 2 bypasses tell us about developer friction?",
    "5. **Flow:** Is 6 minutes of security time acceptable when the pipeline takes 21 minutes?",
    "",
    "---",
    "",
    "### 📦 Artifacts",
    "",
    "- `devsecops-results.sarif` — machine-readable security findings",
    "- `devsecops-metrics-report.txt` — raw metrics output",
    "- GitHub **Code scanning** — SARIF findings published by the workflow",
]

print("\n".join(lines))
